title: Jacob Charles Wilson
description: Freelance Arts Writer

url: https://jacobcharleswilson.com
enforce_ssl: jacobcharleswilson.com
email: hello@jacobcharleswilson.com
twitter:
  username: jclwilson
github:
  username: jclwilson
instagram:
  username: jclwilson
permalink: "/:title"
markdown: kramdown

cdn_url: https://s3.eu-west-2.amazonaws.com/jclwilson-cdn/

plugins:
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-sitemap

# Default Post Front Matter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: post
      latest_content: false
      # Dublin Core Metadata
      creator: Jacob Charles Wilson # An entity primarily responsible for making the resource.
      language: English # A language of the resource.
      rights: # Information about rights held in and over the resource.
