---
title: Jacob Charles Wilson
description: Freelance Arts Writer

url: https://jacobcharleswilson.com
enforce_ssl: jacobcharleswilson.com
email: hello@jacobcharleswilson.com
twitter:
  username: jclwilson
github:
  username: jclwilson
instagram:
  username: jclwilson
permalink: "/:title"
markdown: kramdown
plugins:
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-sitemap
